service: pledge-rest-api-cors

package:
  exclude:
    - node_modeules

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 20
  versionFunctions: false
  memorySize: 512
  environment:
    NODE_ENV: development

functions:

  post:
    handler: build/routes/create.post
    events:
      - http:
          path: /client
          method: post
          cors: true


  list:
    handler: build/routes/list.get
    events:
      - http:
          path: client
          method: get
          cors: true

          request:
            parameters:
              querystrings:
                limit: false
                offset: false

  get:
    handler: build/routes/get.getOne
    events:
      - http:
          path: client/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  update:
    handler: build/routes/update.put
    events:
      - http:
          path: client/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true      

  delete:
    handler: build/routes/delete.deleteClient
    events:
      - http:
          path: client/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
