service: pledge-rest-api-cors

package:
  exclude:
    - node_modeules

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 20
  versionFunctions: false
  memorySize: 512
  environment:
    NODE_ENV: development

functions:
  check:
    handler: build/routes/preSignup.check
    events:
      - http:
          path: auth
          method: post

  post:
    handler: build/routes/clients/create.post
    events:
      - http:
          path: /client
          method: post
          cors: true


  list:
    handler: build/routes/clients/list.get
    events:
      - http:
          path: client
          method: get
          cors: true

          request:
            parameters:
              querystrings:
                limit: false
                offset: false

  get:
    handler: build/routes/clients/get.getOne
    events:
      - http:
          path: client/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  update:
    handler: build/routes/clients/update.put
    events:
      - http:
          path: client/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true      

  delete:
    handler: build/routes/clients/delete.deleteClient
    events:
      - http:
          path: client/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  
  postTransaction:
    handler: build/routes/transactions/create.post
    events:
      - http:
          path: /transactions
          method: post
          cors: true

  listTransactions:
    handler: build/routes/transactions/list.get
    events:
      - http:
          path: /transactions
          method: get
          cors: true
