service: serverless-rest-api-cors

package:
  exclude:
    - node_modeules

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 20
  versionFunctions: false
  memorySize: 512
  environment:
    NODE_ENV: development

functions:
  check:
    handler: build/routes/preSignup.check
    events:
      - http:
          path: auth
          method: post

  post:
    handler: build/routes/clients/create.post
    events:
      - http:
          path: /client
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key


  list:
    handler: build/routes/clients/list.get
    events:
      - http:
          path: client
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key
          request:
            parameters:
              querystrings:
                limit: false
                offset: false

  update:
    handler: build/routes/clients/update.put
    events:
      - http:
          path: client/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key
          request:
            parameters:
              paths:
                id: true

  delete:
    handler: build/routes/clients/delete.deleteClient
    events:
      - http:
          path: client/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key
          request:
            parameters:
              paths:
                id: true
  
  postTransaction:
    handler: build/routes/transactions/create.post
    events:
      - http:
          path: /transaction
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key

  listTransactions:
    handler: build/routes/transactions/list.get
    events:
      - http:
          path: /transactions/query
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key

  sumTransactions:
    handler: build/routes/transactions/summary.get
    events:
      - http:
          path: /transactions
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key
          method: get
          request:
            parameters:
              paths:
                date: true

  getTransaction:
    handler: build/routes/transactions/get.getOne
    events:
      - http:
          path: /transaction
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - serverless-api-key
          method: get